---
title: "Attack of the clones basic genotype change analysis"
author: "Peter Euclide"
date: "May 23, 2019"
output: html_document
---

```{r setup, include=FALSE}

library(tidyr)
library(dplyr)
library(ggplot2)
library(ggpubr)
library(knitr)

```


```{r read in data, include=F}

## Read in filtered datasets created with script 1_locus_selection.rmd

#-----

CF_parsed_genotype_calls_filtered_long <- read.table("./walleye/CF_wa_parsed_genotype_calls_filtered_long")
NO_CF_parsed_genotype_calls_filtered_long <- read.table("./walleye/NO_CF_wa_parsed_genotype_calls_filtered_long")

#-----

CF_parsed_read_depth_filtered_long <- read.table("./walleye/CF_wa_parsed_read_depth_filtered_long")
NO_CF_parsed_read_depth_filtered_long <- read.table("./walleye/NO_CF_wa_parsed_read_depth_filtered_long")

#-----
# these data files are not used for any core analysis

#CF_reads_per_allele_filtered_long <- read.table("./walleye/CF_wa_reads_per_allele_RAW_filtered_long")
#NO_CF_reads_per_allele_filtered_long <- read.table("./walleye/NO_CF_wa_reads_per_allele_RAW_filtered_long")


```


```{r identify genotype change type, include=F}

# combine calls so calls are side by side in columns

comb_calls_dataset <- cbind(NO_CF_parsed_genotype_calls_filtered_long, CF_parsed_genotype_calls_filtered_long$call)
colnames(comb_calls_dataset)[c(8,10)]=c("call_NO_CF","call_CF") #rename columns

comb_calls_dataset$changeType <- paste(as.character(comb_calls_dataset$call_NO_CF),as.character(comb_calls_dataset$call_CF), sep = "->")

# to make things simple, just change anything that stayed the same to "NO_CHANGE"
##   call key: 0 = homo A1, 1 = het, 2 = homo A2, -9 = no call

comb_calls_dataset[comb_calls_dataset$changeType %in% c("0->0",  "2->2",  "1->1", "-9->-9"),"changeType"] <-  "NO_CHANGE"
comb_calls_dataset <- droplevels(comb_calls_dataset)


# add simplified changeType column

comb_calls_dataset$changeType_b <- "NO_CHANGE"


comb_calls_dataset[comb_calls_dataset$changeType %in% c("0->1", "2->1"),"changeType_b"] <- "homo -> het"
comb_calls_dataset[comb_calls_dataset$changeType %in% c("1->0", "1->2"),"changeType_b"] <- "het -> homo"
comb_calls_dataset[comb_calls_dataset$changeType %in% c("0->-9", "2->-9"),"changeType_b"] <- "homo -> no_call"
comb_calls_dataset[comb_calls_dataset$changeType %in% c("1->-9"),"changeType_b"] <- "het -> no_call"
comb_calls_dataset[comb_calls_dataset$changeType %in% c("-9->0", "-9->2"),"changeType_b"] <- "no_call -> homo"
comb_calls_dataset[comb_calls_dataset$changeType %in% c("-9->1"),"changeType_b"] <- "no_call -> het"
comb_calls_dataset[comb_calls_dataset$changeType %in% c("0->2", "2->0"),"changeType_b"] <- "homo_A1 -> homo_A2"


```


```{r table of call change types, echo =F}
# table of genotype changes
change_by_lib <- comb_calls_dataset %>%
  group_by(lib, changeType_b) %>%
  summarise (n = n()) %>%
  mutate(freq = (n / sum(n))*100) %>%
  arrange(lib, freq)

colnames(change_by_lib) <- c("Library", "Change_Type", "Count", "Percent" )

kable(change_by_lib, digits = 3)

```


```{r GT change by individual, echo = F, fig.width= 12, fig.height=7}

# plot the average GT change rate by sample. This data is the data used in Figure 4 of the manuscript.


# add column defining if a change has occured of any sort
comb_calls_dataset$change <- comb_calls_dataset$changeType !="NO_CHANGE"

## calculate number of changes by sample ----

num_loci <- length(unique(comb_calls_dataset$ID))

GT_changeBysample <- comb_calls_dataset %>% group_by(lib, sample) %>% 
  summarise(per_change = ((sum(change)/num_loci))*100,
            #maf = as.numeric(unique(gsub("AF=", "", Allele.Frequency))),
            GT_rate_noCF = sum(call_NO_CF != -9)/length(sample),
            GT_rate_CF = sum(call_CF != -9)/length(sample))


ggplot(GT_changeBysample, aes(x = reorder(sample, -as.numeric(lib)), y =  per_change, color = GT_rate_noCF, shape = lib))+
  geom_point(stat = "identity", size = 3, alpha = .8)+
  theme_bw()+
    labs(title = "Total percent call change by sample",  x = "Sample", y = "% loci changed")+
    theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 7),
          plot.title = element_text(size = 14),
          text = element_text(size = 20),
          legend.position = "bottom")


```


```{r GT change by locus, echo=F, fig.width=12, fig.height=7}

# This is the dataset used to create supplemntary Figure S1 and conduct predictive variable analysis for locus change rate results.

## calculate number of changes by locus ----

numInds <- length(unique(comb_calls_dataset$sample))

GT_changeBylocus <-comb_calls_dataset %>% 
  group_by(ID) %>% 
  summarise(per_change = (sum(change)/numInds*100),
            sum_inds = sum(change),
            maf = as.numeric(unique(gsub("AF=", "", Allele.Frequency) )),
            GT_rate = sum(call_NO_CF != -9)/length(ID),
            sumNoCall= sum(call_NO_CF != -9),
            lengthID =length(ID))


#plot changes by sample
(change_by_locus_plot <- ggplot(data=GT_changeBylocus, aes(x = ID, y = per_change, color = GT_rate)) +
  geom_point(stat = "identity", alpha = 0.2, size = 2)+
  labs(title = "Percent of individuals where genotype call was changed by locus", x = "Locus", y = "% individuals changed GT")+
  theme_classic()+
    theme(text = element_text(size = 20),
          plot.title = element_text(size = 14),
           axis.text.x = element_blank(),
           legend.position = "bottom"))


```


```{r read depth and genotype change, echo = F, fig.height = 8, fig.width=10}
#CF_ReadDepth <- CF_parsed_read_depth_filtered_long[,c("ID", "sample", "depth")]

#summarize read depth by sample: ----

CF_ReadDepthBySample <- CF_parsed_read_depth_filtered_long %>%
  group_by(sample) %>%
    summarise(mean_depth = mean(depth))

NO_CF_ReadDepthBySample <- NO_CF_parsed_read_depth_filtered_long %>%
  group_by(sample) %>%
    summarise(mean_depth = mean(depth))

#merge with GT change by sample


CF_RD_GT_changeBysample <- full_join(GT_changeBysample, CF_ReadDepthBySample)
NO_CF_RD_GT_changeBysample <- full_join(GT_changeBysample, NO_CF_ReadDepthBySample)

## generate clone filtered and non-clone filtered plots to look at the relationship between read depth and change rate. 

# plot 
CF_GT_change_by_read_depth_plot_sample <- ggplot(CF_RD_GT_changeBysample, aes(x = mean_depth, y = per_change, color = GT_rate, shape = lib))+
  geom_point(alpha = 0.8, size = 3)+
  theme_bw()+
  labs(x = "Mean read depth", y = "Percent calls changed", title = "clone filtered")


NO_CF_GT_change_by_read_depth_plot_sample <- ggplot(NO_CF_RD_GT_changeBysample, aes(x = mean_depth, y = per_change, color = lib))+
  geom_point(alpha = 0.5, size = 3)+
  scale_color_manual(values =c("#E69F00", "#56B4E9"))+
  theme_bw()+
  labs(x = "Mean read depth", y = "Percent calls changed", title = "Not clone filtered")


# summarize read depth by locus: ----

CF_ReadDepthByLocus <- CF_parsed_read_depth_filtered_long %>%
  group_by(ID) %>%
    summarise_at(vars(depth), funs(n(), mean(.) ))

NO_CF_ReadDepthByLocus <- NO_CF_parsed_read_depth_filtered_long %>%
  group_by(ID) %>%
    summarise_at(vars(depth), funs(n(), mean(.) ))


CF_RD_GT_changeByLocus <- full_join(GT_changeBylocus, CF_ReadDepthByLocus)
NO_CF_RD_GT_changeByLocus <- full_join(GT_changeBylocus, NO_CF_ReadDepthByLocus)

# plot read depth by locus GT change ----

CF_GT_change_by_read_depth_plot_locus <- ggplot(CF_RD_GT_changeByLocus, aes(x = mean, y = per_change, color = lib))+
  geom_point(alpha = 0.2, size = 2)+
  scale_color_manual(values =c("#E69F00", "#56B4E9"))+
  theme_bw()+
  labs(x = "Mean read depth", y = "Percent calls changed", title = "Clone filtered")

NO_CF_GT_change_by_read_depth_plot_locus <- ggplot(NO_CF_RD_GT_changeByLocus, aes(x = mean, y = per_change, color = lib))+
  geom_point(alpha = 0.2, size = 2)+
  scale_color_manual(values =c("#E69F00", "#56B4E9"))+
  theme_bw()+
  labs(x = "Mean read depth", y = "Percent calls changed", title = "Not Clone filtered")

# combiine all four plots to make single 4 panel figure

ggarrange(NO_CF_GT_change_by_read_depth_plot_sample, CF_GT_change_by_read_depth_plot_sample,NO_CF_GT_change_by_read_depth_plot_locus, CF_GT_change_by_read_depth_plot_locus,
          labels = c("A", "B", "C", "D"),
          ncol = 2, nrow = 2,
          common.legend = T,
          legend = "bottom")

```